sudo: true
dist: trusty
os: linux
language: minimal
env:
  global:
  - MAKEJOBS=-j3
  - DOCKER_NAME_TAG=ubuntu:18.04
  - DOCKER_PACKAGES="python3-zmq libssl-dev libevent-dev libboost-system-dev libboost-filesystem-dev libboost-chrono-dev libboost-test-dev libboost-thread-dev lcov build-essential libtool autotools-dev automake pkg-config bsdmainutils"
  - LC_ALL=C.UTF-8
before_install:
    - export PATH=$(echo $PATH | tr ':' "\n" | sed '/\/opt\/pyenv/d' | tr "\n" ":" | sed "s|::|:|g") # work around travis python3.5 bug
    - travis_retry sudo apt-get update
    - travis_retry sudo apt-get install --no-install-recommends --no-upgrade -qq python3-requests
install:
    - git clone https://github.com/bitcoin/bitcoin
    - git config user.name "Travis/${TRAVIS_REPO_SLUG}"
    - git config user.email "travis@none.org"
    - git remote add origin_git https://github.com/${TRAVIS_REPO_SLUG}  # Add remote so we can push there
    - git fetch origin_git
    - env | grep -E '^(LC_ALL)' | tee /tmp/env
    - travis_retry docker pull "$DOCKER_NAME_TAG"
    - DOCKER_ID=$(docker run -idt --mount type=bind,src=$TRAVIS_BUILD_DIR,dst=$TRAVIS_BUILD_DIR -w $TRAVIS_BUILD_DIR --env-file /tmp/env $DOCKER_NAME_TAG)
    - DOCKER_EXEC () { docker exec $DOCKER_ID bash -c "cd $PWD && $*"; }
    - travis_retry DOCKER_EXEC apt-get update
    - travis_retry DOCKER_EXEC apt-get install --no-install-recommends --no-upgrade -qq $DOCKER_PACKAGES
before_script:
    - cd bitcoin
    - export MASTER_COMMIT=$(git log --format='%H' -1)
    - DOCKER_EXEC ./autogen.sh
    - cat ../patch_makefile | git apply
    - mkdir build && cd build
    - DOCKER_EXEC ../configure --disable-wallet --disable-tests --disable-zmq --disable-bench --enable-lcov --enable-lcov-branch-coverage
    - DOCKER_EXEC make $MAKEJOBS
    - DOCKER_EXEC make cov
script:
    - cd ../../
    - git checkout master && git reset --hard origin_git/master_init
    - cp -r ./bitcoin/build/*coverage* ./
    - git add ./*coverage* && git commit -m 'Update nightly coverage results'
    - git push origin_git master -f
